"use client"


import Link from "next/link"
import { usePathname } from "next/navigation"
import { use } from "react"
import { ChannelVideos } from "./ChannelVideos"

type Channel = {
    "author": string,
    "authorId": string,
    "authorUrl": string,
    "authorVerified": boolean,
    "authorBanners": ImageObject[],
    "authorThumbnails": ImageObject[],
  
    "subCount": number, // Integer
    "totalViews": number, // Integer
    "joined": number, // Unix timestamp
  
    "autoGenerated": boolean,
    "isFamilyFriendly": boolean,
  
    "description": string,
    "descriptionHtml": string,
    "allowedRegions": string[],
  
    "tabs": string[],
  
    "latestVideos": Video[],
    "relatedChannels": [
      // One or more ChannelObject
    ]
  }
  
  type ImageObject = {
    "url": string,
    "width": number, // Integer
    "height": number // Integer
  }
  
  type Video = {
    "type": "video", // Constant
  
    "title": string,
    "videoId": string,
  
    "author": string,
    "authorId": string,
    "authorUrl": string,
    "authorVerified": boolean,
  
    "videoThumbnails": ThumbnailObject[],
  
    "description": string,
    "descriptionHTML": string,
  
    "viewCount": number, // Integer
    "viewCountText": string,
    "lengthSeconds": number, // Integer
  
    "published": number, // Unix timestamp
    "publishedText": string,
  
    // Only available on premiered videos
    "premiereTimestamp": number, // Unix timestamp
  
    "liveNow": boolean,
    "premium": boolean,
    "isUpcoming": boolean
  }
  
  type ThumbnailObject = {
    "quality": string,
    "url": string,
    "width": number, // Integer
    "height": number // Integer
  }

export function ChannelContents({focus, channelID}: {focus:string, channelID:string}) {
    return(
      <div>
        <div className="flex align-center gap-2 mt-6 mb-2 h-8 px-10">
          <Link href={""} className={`border-b-2 px-1 ${focus == "videos" ? "" : ""}`}>動画</Link>
          <Link href={""} className={`border-b-2 px-1 ${focus == "videos" ? "" : ""}`}>再生リスト</Link>
          <Link href={""} className={`border-b-2 px-1 ${focus == "videos" ? "" : ""}`}>ストリーム</Link>
        </div>
        <ChannelVideos channelID={channelID}/>
      </div>
    )
}