"use client"

import Link from "next/link"
import { usePathname } from "next/navigation";
import { useState } from "react";
import { ChannelVideos } from "./ChannelVideos"

type Channel = {
    "author": string,
    "authorId": string,
    "authorUrl": string,
    "authorVerified": boolean,
    "authorBanners": ImageObject[],
    "authorThumbnails": ImageObject[],
  
    "subCount": number, // Integer
    "totalViews": number, // Integer
    "joined": number, // Unix timestamp
  
    "autoGenerated": boolean,
    "isFamilyFriendly": boolean,
  
    "description": string,
    "descriptionHtml": string,
    "allowedRegions": string[],
  
    "tabs": string[],
  
    "latestVideos": Video[],
    "relatedChannels": [
      // One or more ChannelObject
    ]
  }
  
  type ImageObject = {
    "url": string,
    "width": number, // Integer
    "height": number // Integer
  }
  
  type Video = {
    "type": "video", // Constant
  
    "title": string,
    "videoId": string,
  
    "author": string,
    "authorId": string,
    "authorUrl": string,
    "authorVerified": boolean,
  
    "videoThumbnails": ThumbnailObject[],
  
    "description": string,
    "descriptionHTML": string,
  
    "viewCount": number, // Integer
    "viewCountText": string,
    "lengthSeconds": number, // Integer
  
    "published": number, // Unix timestamp
    "publishedText": string,
  
    // Only available on premiered videos
    "premiereTimestamp": number, // Unix timestamp
  
    "liveNow": boolean,
    "premium": boolean,
    "isUpcoming": boolean
  }
  
  type ThumbnailObject = {
    "quality": string,
    "url": string,
    "width": number, // Integer
    "height": number // Integer
  }

export function ChannelContents({channelID}: {channelID:string}) {
  const [channelTab, setChannelTab] = useState<string>("videos");
  const changeTab = (tab:string) => {
    setChannelTab(tab);
  }
    return(
      <div>
        <div className="flex align-center gap-2 mt-6 mb-2 h-8 px-10">
          <button onClick={() => {changeTab("videos")}} className={`border-b-2 px-1 ${channelTab == "videos" ? "" : ""}`}>動画</button>
          <button onClick={() => {changeTab("playlists")}} className={`border-b-2 px-1 ${channelTab == "playlists" ? "" : ""}`}>再生リスト</button>
          <button onClick={() => {changeTab("streams")}} className={`border-b-2 px-1 ${channelTab == "streams" ? "" : ""}`}>ストリーム</button>
        </div>
        <ChannelVideos channelID={channelID}/>
      </div>
    )
}